/* This file is loaded by play.html. It should specify the size and location
   of each image resource used by the game.

   The StaticImageInfo object should have integer keys (Glk image numbers).
   These should map to Javascript objects which look like:

   {
     "image": INT, 
     "url": URLSTRING,
     "alttext": STRING,
     "width": INT,
     "height": INT
   }

   The image number must match the key. (Yes, it's redundant, just do it.) The
   alttext is an optional string describing the image (for non-graphical
   displays and visually impaired users.) The width and height are the image
   size -- these fields are required! And the url should be a URL from which
   the image resource can be loaded. This may be an absolute URL, or relative
   to play.html.

   This information is not yet generated by Inform. If your game contains
   graphics, you can manually edit this file to include all the image
   data. Alternatively, use the "giload" command of blorbtool.py:

   python blorbtool.py GAME.materials/Release/GAME.gblorb giload GAME.materials/Release/interpreter interpreter
*/

StaticImageInfo = {
	{
	 "image": 3, 
     "url": "laboratory.jpg",
     "alttext": "Laboratory",
     "width": 1000,
     "height": 750	
	}
	{
	 "image": 4, 
     "url": "waveBioReactor.jpg",
     "alttext": "Wave Bioreactor",
     "width": 879,
     "height": 441	
	}
	{
	 "image": 5, 
     "url": "biomedicalFridge.jpg",
     "alttext": "Refridgerator",
     "width": 480,
     "height": 480	
	}
	{
	 "image": 6, 
     "url": "bioreactorTank.jpg",
     "alttext": "Stir Tank Bioreactor",
     "width": 430,
     "height": 450	
	}
	{
	 "image": 7, 
     "url": "incubator.jpg",
     "alttext": "Incubator",
     "width": 360,
     "height": 480	
	}
};
